### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by dstegelman**
- Tests and Travis!
- Python 3!
- CAS V3 support

### CODE REVIEW

**Comment by chadgh** [comment]
This looks great. Can't wait to see it released. Is there anything I can do to help this move along?

**Comment by dstegelman** [comment]
My plan is for this week.  I've been testing this internally but could any additional testing would be appreciated!

**Comment by chadgh** [comment]
I don't know if this matters or not, but the README seems to leave out a few steps on setup. There isn't a mention of the AUTHENTICATION_BACKEND settings being set or the urls.py file being updated. Unless I'm missing something, both of those seem to be required.

**Comment by dstegelman** [comment]
@chadgh Thanks.  I'll get the README updated and we should be good to release this week.

**Pull request merged**
