### PR TITLE
Handles CAS v3 protocol

### PR DESCRIPTION
**Pull request by leleuj**
This is a very simple implementation to handle the CAS protocol v3 (extra attributes returned in the XML payload). The callback function must be used to deal with the extra attributes received: `tree[0][1].getchildren()`.
The `CAS_VERSION` can now be set to 3 to change the endpoint used by the CAS server and to retrieve the user attributes.

Although I tested this change, I'm a newbie in Python. Just let me know if something is wrong.

### CODE REVIEW

**Comment by dstegelman** [comment]
@leleuj thanks for contributing.  There are some (very small) tests ran by Travis that have been merged to develop.  Could you update this branch with develop and push so that tests are ran?

**Comment by leleuj** [comment]
@dstegelman: I reopened a new PR #35 as I messed this one.

I wanted to locally run the tests using `python run_tests.py`, but I always get the following error: "ImportError: No module named factory" even after installing the factory module: `pip install factory`. Is there something special to do? May I suggest to add something about the tests in the `README.md`?

**Comment by dstegelman** [comment]
in the future to test locally first

```
pip install -r dev-requirements.txt
```

I'll update the readme

**Comment by leleuj** [comment]
OK. Thx. Tests pass.

**Pull request closed without merging**
