### PR TITLE
Ready for Python 3

### PR DESCRIPTION
**Pull request by chadgh**
I've done all I know how to do with getting the code working in both Python 2 and Python 3. I can't quite figure out how to run the tests completely successfully, but the code is working for me in an application in both Python 2.7 and Python 3.3.

I'm willing to do more for this to get accepted. I'm so glad to see kstateome doing something about this repo. Thanks.

### CODE REVIEW

**Comment by dstegelman** [comment]
Thanks for the contribution!

I'm out of the office until Tuesday but I will take a look at this as soon as I get back.

**Comment by dstegelman** [comment]
@chadgh So I'd really like to get some tests up and running through travis before I merge this (and any other commits as well).  My plan is to have some sort of tests running by the end of next week and then **hopefully** get this merged in.  

Thanks again for your contribution.

**Comment by chadgh** [comment]
Sounds good. Let me know if there is anything I need to change as you do the testing.

Thanks again.

**Comment by dstegelman** [comment]
@chadgh thanks for contributing.  There are some (very small) tests ran by Travis that have been merged to develop.  Could you update this branch with develop and push so that tests are ran?

**Comment by chadgh** [comment]
I hope I did that correctly. I've never used Travis before. Commit 8aa5383 failed so I fixed the issue and committed those changes.

Assuming this build passes the tests, is the plan to merge these changes in? I noticed that Travis wasn't going to test anything against Python 3.X. Will that be added later?

**Comment by dstegelman** [comment]
Yes.  I'd like to merge these in.  Since this is the first build with Python 3 support could you do the following:

on this line https://github.com/kstateome/django-cas/blob/develop/.travis.yml#L4

add 

```
- "3.3"
- "3.4"
```

This way Travis will go ahead and check Python 3.

**Comment by dstegelman** [comment]
Thank you, I'll do a final review of this tomorrow.

**Comment by chadgh** [comment]
Sweet! Thanks so much for maintaining this project.

**Pull request merged**
